export const FETCH_GET_SINGLE_USER_SUCCESS = 'FETCH_GET_SINGLE_USER_SUCCESS';
export const FETCH_GET_SINGLE_USER_FAILURE = 'FETCH_GET_SINGLE_USER_FAILURE';
export const FETCH_GET_SINGLE_USER_REQUEST = 'FETCH_GET_SINGLE_USER_REQUEST';
